version: '3.8'
services:
  nest_mongo_backend:
    container_name: nest_mongo_backend
    image: saidev/nest-mongo:0.0.1
    build:
      context: .
    ports:
      - '3000:3000'
    environment:
      - EMONGO_DB_URL=mongodb://localhost:27017/livenestdb
